import { AssessmentConfig } from "./types";

export const assessmentConfig: AssessmentConfig = {
  pillars: [
    { id: "customer", name: "Lead Engagement & Speed" },
    { id: "operations", name: "Operational Focus & Time Efficiency" },
    { id: "revenue", name: "Appointment Reliability & Conversion" },
    { id: "data", name: "Systems & Automation Maturity" },
    { id: "informative", name: "Additional Information" },
  ],
  questions: [
    // Q1-Q11: SCORED QUESTIONS
    {
      id: "q1-engagement",
      pillar: "customer",
      text: "How are you engaging new leads at the point of enquiry?",
      isScored: true,
      options: [
        { id: "ai", label: "Instant conversational AI for assessment and scheduling", answerId: "A" },
        { id: "automated-basic", label: "Automated instant SMS/Email on submission only", answerId: "B" },
        { id: "manual", label: "Manual sales team outreach only / automation plus sales team outreach", answerId: "C" },
        { id: "calendar", label: "Calendar function (e.g. Calendly) where clients pick time/date to schedule appointment", answerId: "D" },
      ],
    },
    {
      id: "q2-response-time",
      pillar: "customer",
      text: "On average, how long does it take from point of enquiry to first conversational engagement for your clients?",
      isScored: true,
      options: [
        { id: "60s", label: "Less than 60 seconds", answerId: "A" },
        { id: "1-10m", label: "1–10 minutes", answerId: "B" },
        { id: "10-60m", label: "10–60 minutes", answerId: "C" },
        { id: "1h-plus", label: "More than 1 hour", answerId: "D" },
      ],
    },
    {
      id: "q3-availability",
      pillar: "customer",
      text: "Can your clients ask questions and book appointments 24/7, 7 days a week?",
      isScored: true,
      options: [
        { id: "yes", label: "Yes", answerId: "A" },
        { id: "no", label: "No", answerId: "B" },
      ],
    },
    {
      id: "q4-show-rate",
      pillar: "revenue",
      text: "What percentage of booked appointments show up?",
      isScored: true,
      options: [
        { id: "0-30", label: "0-30%", answerId: "A" },
        { id: "30-50", label: "30-50%", answerId: "B" },
        { id: "50-70", label: "50-70%", answerId: "C" },
        { id: "80-plus", label: "80%+", answerId: "D" },
        { id: "unknown", label: "I don't know", answerId: "E" },
      ],
    },
    {
      id: "q5-transaction-rate",
      pillar: "revenue",
      text: "What percentage of new clients who engage with your business 'transact' with your service?",
      isScored: true,
      options: [
        { id: "90-100", label: "90–100%", answerId: "A" },
        { id: "80-90", label: "80–90%", answerId: "B" },
        { id: "70-80", label: "70–80%", answerId: "C" },
        { id: "60-70", label: "60–70%", answerId: "D" },
        { id: "sub-50", label: "50% or less", answerId: "E" },
        { id: "unknown", label: "I don't know / we don't track this data", answerId: "F" },
      ],
    },
    {
      id: "q6-primary-role",
      pillar: "operations",
      text: "How much of your team's time is spent performing their primary role (e.g. amount of time your sales team are actually on sales calls vs. other non-revenue generating tasks)?",
      isScored: true,
      options: [
        { id: "90-100", label: "90–100%", answerId: "A" },
        { id: "80-90", label: "80–90%", answerId: "B" },
        { id: "70-80", label: "70–80%", answerId: "C" },
        { id: "60-70", label: "60–70%", answerId: "D" },
        { id: "sub-50", label: "50% or less", answerId: "E" },
        { id: "unknown", label: "I don't know / we don't track this data", answerId: "F" },
      ],
    },
    {
      id: "q7-follow-up-time",
      pillar: "operations",
      text: "On average, how much time per week does a client facing team member spend engaging leads who did not book an appointment, or did not attend a scheduled appointment?",
      isScored: true,
      options: [
        { id: "none", label: "None", answerId: "A" },
        { id: "60m", label: "60 minutes or less per week", answerId: "B" },
        { id: "1-4h", label: "1-4 hours per week", answerId: "C" },
        { id: "4h-plus", label: "More than 4 hours per week", answerId: "D" },
        { id: "unknown", label: "I don't know", answerId: "E" },
      ],
    },
    {
      id: "q8-repetitive-tasks",
      pillar: "operations",
      text: "On average, how much time per week does a relevant team member spend performing standard repetitive tasks such as document requests, data entry and KPI/stats tracking?",
      isScored: true,
      options: [
        { id: "none", label: "None", answerId: "A" },
        { id: "60m", label: "60 minutes or less per week", answerId: "B" },
        { id: "1-5h", label: "1-5 hours per week", answerId: "C" },
        { id: "5h-plus", label: "More than 5 hours per week", answerId: "D" },
        { id: "unknown", label: "I don't know", answerId: "E" },
      ],
    },
    {
      id: "q9-kpi-tracking",
      pillar: "data",
      text: "How would you rate your company key metric tracking?",
      isScored: true,
      options: [
        { id: "perfect", label: "Perfect – we have sight of all vital stats in one dashboard including time to lead engagement, client DNA and conversion data and minimal manual input is required.", answerId: "A" },
        { id: "average", label: "Average – we have sight of some key metrics in one place, and it either requires manual input or a combination of manual input and automation.", answerId: "B" },
        { id: "poor", label: "Poor – we don't have an adequate display or tracking for key metrics, and mostly rely on manual input.", answerId: "C" },
      ],
    },
    {
      id: "q10-documents",
      pillar: "data",
      text: "If your business sends and receives client documents or requests signatures:",
      isScored: true,
      options: [
        { id: "fully-automated", label: "These are fully automated in one company branded portal which handles all document upload requests and signatures. Templates are used to eliminate manual repetition", answerId: "A" },
        { id: "third-party", label: "These are automated through a third party subscription platform", answerId: "B" },
        { id: "manual", label: "We request any documents or signatures via email from the client", answerId: "C" },
        { id: "not-applicable", label: "We don't send or receive documents as part of our service.", answerId: "D" },
      ],
    },
    {
      id: "q11-overall-automation",
      pillar: "data",
      text: "What best describes your current situation? (not all aspects may be relevant, just pick the best fit)",
      isScored: true,
      options: [
        { id: "complete", label: "AI does the hard work — Instant client triage, response and booking. 90% of appointments attended. Zero repetitive tasks. Zero GDPR risk or time wastage on document requests. Elite KPI monitoring and AI marketing strategy including multivariate test systems. ROAS/CPA well above industry standard.", answerId: "A" },
        { id: "partial", label: "AI does some of the work — Part automated client engagement with 80+% appointment attendance. Minimal repetitive tasks and admin. KPI monitoring and marketing processes are acceptable to adequate. ROAS/CPA acceptable or improvement required.", answerId: "B" },
        { id: "none", label: "AI not in place — Manual client engagement with less than 80% appointment attendance. High repetitive task and admin requirements. KPI monitoring and marketing are adequate or poor. ROAS/CPA acceptable or improvement required.", answerId: "C" },
        { id: "other", label: "Other — If the above are not relevant to your model, please provide a short qualitative overview.", answerId: "D", hasTextInput: true },
      ],
    },
    // Q12-Q14: INFORMATIVE QUESTIONS (not scored)
    {
      id: "q12-desired-outcome",
      pillar: "informative",
      text: "What best describes the outcome you're looking for?",
      isScored: false,
      options: [
        { id: "time-saving", label: "Time saving (Deflection ROI). AI to reduce some or all of the following: manual data entry, client triage/comms/engagement/management, document requests, manual chasing and/or other repetitive non-revenue generating tasks.", answerId: "A" },
        { id: "revenue", label: "Revenue Increase. Increase revenue without additional marketing spend through enhanced conversion rates, reduced business loss to competitors and/or marketing efficacy improvements.", answerId: "B" },
        { id: "both", label: "A combination of deflection ROI and revenue increase to maximize organizational efficiency.", answerId: "C" },
        { id: "none", label: "None of the above, we're fine as we are", answerId: "D" },
        { id: "other", label: "Other, please specify:", answerId: "E", hasTextInput: true },
      ],
    },
    {
      id: "q13-barriers",
      pillar: "informative",
      text: "What has prevented you from implementing comprehensive AI strategy previously? (Select all that apply)",
      isScored: false,
      isMultiSelect: true,
      options: [
        { id: "tech-failed", label: "Other solutions did not meet our standards or adequately solve a problem", answerId: "A" },
        { id: "no-roi", label: "Other solutions did not provide an ROI guarantee for our investment", answerId: "B" },
        { id: "not-comprehensive", label: "Other services specialize in 1 AI implementation rather than a comprehensive strategy tailored to our specific needs", answerId: "C" },
        { id: "confusing", label: "We find AI confusing and lack technical understanding", answerId: "D" },
        { id: "job-concern", label: "We're concerned AI will replace human roles", answerId: "E" },
        { id: "other", label: "Other, please specify", answerId: "F", hasTextInput: true },
      ],
    },
    {
      id: "q14-solution-type",
      pillar: "informative",
      text: "Which type of solution would best suit your needs?",
      isScored: false,
      options: [
        { id: "full-service", label: "I want to be at the cutting edge but don't want to pay big AI salaries. A team of AI directors to handle in-depth system/processes review, proposal/implementation with clear associated ROI and long-term commitment to ongoing improvements", answerId: "A" },
        { id: "implementation-only", label: "I'm keen to consider AI implementation(s) only, such as your 24/7 conversational triage system, but I do not require ongoing support via your fractional director service", answerId: "B" },
        { id: "directors-only", label: "I'm happy with our existing systems, but would like to learn more about fractional AI directors as a standalone service", answerId: "C" },
        { id: "not-concerned", label: "I'm not currently concerned about the opportunity loss in time, revenue and lost business", answerId: "D" },
        { id: "other", label: "Other, please specify (e.g. sales training / SOPs, marketing optimisation/\"I just want my business to make more money without spending more on ads\"):", answerId: "E", hasTextInput: true },
      ],
    },
  ],
};
