import { AssessmentConfig } from "./types";

export const assessmentConfig: AssessmentConfig = {
  pillars: [
    { id: "customer", name: "Lead Engagement & Speed" },
    { id: "operations", name: "Operational Focus & Time Efficiency" },
    { id: "revenue", name: "Appointment Reliability & Conversion" },
    { id: "data", name: "Systems & Automation Maturity" },
    { id: "informative", name: "Additional Information" },
  ],
  questions: [
    // Q1-Q11: SCORED QUESTIONS
    {
      id: "q1-engagement",
      pillar: "customer",
      text: "How are you engaging new leads at the point of enquiry?",
      isScored: true,
      options: [
        { id: "ai", label: "Instant conversational AI for assessment and scheduling", answerId: "A" },
        { id: "automated-basic", label: "Automated instant SMS/Email on submission only", answerId: "B" },
        { id: "manual", label: "Manual sales team outreach only / automation plus sales team outreach", answerId: "C" },
        { id: "calendar", label: "Calendar function (e.g. Calendly) where clients pick time/date to schedule appointment", answerId: "D" },
      ],
    },
    {
      id: "q2-response-time",
      pillar: "customer",
      text: "On average, how long does it take from point of enquiry to first conversational engagement for your clients?",
      isScored: true,
      options: [
        { id: "60s", label: "Less than 60 seconds", answerId: "A" },
        { id: "10m", label: "Less than 10 minutes", answerId: "B" },
        { id: "1h", label: "Less than 1 hour", answerId: "C" },
        { id: "1h-plus", label: "More than 1 hour", answerId: "D" },
      ],
    },
    {
      id: "q3-availability",
      pillar: "customer",
      text: "Can your clients ask questions and book appointments 24/7, 7 days a week?",
      isScored: true,
      options: [
        { id: "yes", label: "Yes", answerId: "A" },
        { id: "no", label: "No", answerId: "B" },
      ],
    },
    {
      id: "q4-show-rate",
      pillar: "revenue",
      text: "What percentage of booked appointments show up?",
      isScored: true,
      options: [
        { id: "0-30", label: "0-30%", answerId: "A" },
        { id: "30-50", label: "30-50%", answerId: "B" },
        { id: "50-70", label: "50-70%", answerId: "C" },
        { id: "80-plus", label: "80%+", answerId: "D" },
        { id: "unknown", label: "I don't know", answerId: "E" },
      ],
    },
    {
      id: "q5-transaction-rate",
      pillar: "revenue",
      text: "What percentage of new clients who engage with your business 'transact' with your service?",
      isScored: true,
      options: [
        { id: "90-100", label: "90-100%", answerId: "A" },
        { id: "70-90", label: "70-90%", answerId: "B" },
        { id: "50-70", label: "50-70%", answerId: "C" },
        { id: "sub-50", label: "Less than 50%", answerId: "D" },
        { id: "unknown", label: "I don't know", answerId: "E" },
      ],
    },
    {
      id: "q6-primary-role",
      pillar: "operations",
      text: "How much of your team's time is spent performing their primary role (e.g. amount of time your sales team are actually on sales calls vs. other non-revenue generating tasks)?",
      isScored: true,
      options: [
        { id: "90-100", label: "90-100%", answerId: "A" },
        { id: "80-90", label: "80-90%", answerId: "B" },
        { id: "70-80", label: "70-80%", answerId: "C" },
        { id: "60-70", label: "60-70%", answerId: "D" },
        { id: "unknown", label: "I don't know", answerId: "E" },
      ],
    },
    {
      id: "q7-follow-up-time",
      pillar: "operations",
      text: "How much time do you or your team spend engaging leads who reached out but did not book an appointment, or did not attend a scheduled appointment?",
      isScored: true,
      options: [
        { id: "none", label: "None", answerId: "A" },
        { id: "60m", label: "60 minutes or less per week", answerId: "B" },
        { id: "1-4h", label: "1-4 hours per week", answerId: "C" },
        { id: "4h-plus", label: "More than 4 hours per week", answerId: "D" },
        { id: "unknown", label: "I don't know", answerId: "E" },
      ],
    },
    {
      id: "q8-repetitive-tasks",
      pillar: "operations",
      text: "How much time do you or your team spend performing standard repetitive tasks such as document requests, data entry and KPI/stats tracking?",
      isScored: true,
      options: [
        { id: "none", label: "None", answerId: "A" },
        { id: "60m", label: "60 minutes or less per week", answerId: "B" },
        { id: "1-5h", label: "1-5 hours per week", answerId: "C" },
        { id: "5h-plus", label: "More than 5 hours per week", answerId: "D" },
        { id: "unknown", label: "I don't know", answerId: "E" },
      ],
    },
    {
      id: "q9-kpi-tracking",
      pillar: "data",
      text: "How would you rate your company KPI target tracking?",
      isScored: true,
      options: [
        { id: "perfect", label: "Perfect - we have sight of all stats on one dashboard, and minimal manual input is required", answerId: "A" },
        { id: "average", label: "Average - it could be displayed better and more of it is manual than we would like", answerId: "B" },
        { id: "poor", label: "Poor - Either no automation or very poor to zero KPI/target tracking with no graphic visualisation", answerId: "C" },
      ],
    },
    {
      id: "q10-documents",
      pillar: "data",
      text: "If your business sends and receives client documents or requests signatures:",
      isScored: true,
      options: [
        { id: "fully-automated", label: "These are fully automated in one company branded portal which handles all document upload requests and signatures. Templates are used to eliminate manual repetition", answerId: "A" },
        { id: "third-party", label: "These are automated through a third party subscription platform", answerId: "B" },
        { id: "manual", label: "We request any documents or signatures via email from the client", answerId: "C" },
      ],
    },
    {
      id: "q11-overall-automation",
      pillar: "data",
      text: "What best describes your current situation? (not all aspects may be relevant, just pick the best fit)",
      isScored: true,
      options: [
        { id: "complete", label: "Complete automation: new clients experience an immediate 2-way triage appointment scheduling, over 80% of appointments are attended with pre-qualified leads and most clients transact. Our team don't perform repetitive admin tasks and we don't waste time or take risks requesting/receiving documents via email. Our sales and marketing including CRO are optimised and our KPI/target data is automated and visible in a simple dashboard", answerId: "A" },
        { id: "partial", label: "Part automation: New clients receive some automated outreach (email/SMS/PDF), appointments are fairly well attended with good to reasonable sales outcomes. Our team perform some repetitive tasks and admin. Our sales and marketing including CRO are reasonable although could be better. KPI/target tracking works, but it takes more time than we would like", answerId: "B" },
        { id: "none", label: "Zero automation: New clients wait for manual outreach or simple automated message. There is no instantaneous 2-way conversation to build trust and engage the client. Our team perform repetitive tasks and time is spent producing emails manually including document requests/receipt. Our sales, KPI tracking and/or marketing may need some work", answerId: "C" },
        { id: "other", label: "Other, please specify:", answerId: "D", hasTextInput: true },
      ],
    },
    // Q12-Q14: INFORMATIVE QUESTIONS (not scored)
    {
      id: "q12-desired-outcome",
      pillar: "informative",
      text: "What best describes the outcome you're looking for?",
      isScored: false,
      options: [
        { id: "time-saving", label: "Time saving (Deflection ROI). Our team waste a lot of time performing repetitive tasks (e.g. data entry, client management, document requests, chasing)", answerId: "A" },
        { id: "revenue", label: "Revenue increase. We'd like to increase revenue without additional marketing spend through targeted AI efficiency upgrades (e.g. reduce CAC, improve CRO)", answerId: "B" },
        { id: "both", label: "A combination of time saving and revenue increase", answerId: "C" },
        { id: "none", label: "None of the above, we're fine as we are", answerId: "D" },
        { id: "other", label: "Other, please specify:", answerId: "E", hasTextInput: true },
      ],
    },
    {
      id: "q13-barriers",
      pillar: "informative",
      text: "What has prevented you from implementing comprehensive AI strategy previously?",
      isScored: false,
      options: [
        { id: "tech-failed", label: "We've tried other platforms/apps and the technology did not meet our standards or solve a problem or evidence sufficient ROI/use case", answerId: "A" },
        { id: "expensive", label: "We've found options are too expensive", answerId: "B" },
        { id: "confusing", label: "We find AI technology confusing and lack any technical understanding", answerId: "C" },
        { id: "no-time", label: "We haven't had time to look into it in enough depth", answerId: "D" },
      ],
    },
    {
      id: "q14-solution-type",
      pillar: "informative",
      text: "Which type of solution would best suit your needs?",
      isScored: false,
      options: [
        { id: "full-service", label: "I want to be at the cutting edge but don't want to pay big AI salaries. A team of AI directors to handle everything including in-depth system/processes review, proposal/implementation with clear associated ROI and long-term commitment to ongoing improvements", answerId: "A" },
        { id: "implementation-only", label: "I'm keen to consider AI implementation(s) only, such as your 24/7 conversational triage system, but I do not require ongoing support via your fractional director service", answerId: "B" },
        { id: "directors-only", label: "I'm happy with our existing systems, but would like to learn more about fractional AI directors as a standalone service", answerId: "C" },
        { id: "not-concerned", label: "I'm not currently concerned about the opportunity loss in time, revenue and lost business", answerId: "D" },
        { id: "other", label: "Other, please specify (e.g. sales training / SOPs, marketing optimisation/\"I just want my business to make more money without spending more on ads\"):", answerId: "E", hasTextInput: true },
      ],
    },
  ],
};
